# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1e463c0be1d131fadc077b8b9de8bd225384c1303ec7ad1c8e6eb1e0af5a29ee261a1a162f97f8273af3fe06b13708fbd94019de5f4ce1f642460569d2efd4

test:
  secret_key_base: cce195a7f5804bfd2a7a4e8281dda37edc229d2173c41a7f7114d4db33364072b32631c885d6be81c4298b598aef0ed8907f807468339f181404545038d027d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
